import { expect, test } from '@playwright/test';

test('reader, author, and operator journeys render through the BFF rewrite', async ({ page }, testInfo) => {
  const origin = new URL(String(testInfo.project.use.baseURL)).origin;
  const anonymous = await page.request.get('/api/novel/admin/dashboard');
  expect(anonymous.status()).toBe(401);
  const readerSession = await page.request.post('/api/novel/session', { data:{ role:'reader' }, headers:{ Origin: origin } });
  expect(readerSession.status()).toBe(200);
  const csrfDenied = await page.request.post('/api/novel/account/checkin', { headers:{ Origin:'https://untrusted.example' } });
  expect(csrfDenied.status()).toBe(403);
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'编辑推荐'})).toBeVisible();
  await expect(page.getByText('星海拾光')).toBeVisible();
  await page.getByRole('link',{name:/开始阅读/}).first().click();
  await expect(page.getByRole('heading',{name:'第一章 旧港'})).toBeVisible();
  await page.getByRole('button',{name:'加入书架'}).click();
  await expect(page.getByRole('button',{name:'已加入书架'})).toBeVisible();
  await page.getByRole('button',{name:'添加书签'}).click();
  await expect(page.getByRole('status')).toContainText('已添加书签');
  await page.getByLabel('发表评论').fill('浏览器端的阅读反馈');
  await page.getByRole('button',{name:'发布'}).click();
  await expect(page.getByRole('status')).toContainText('评论已发布');
  await expect(page.getByText('浏览器端的阅读反馈').last()).toBeVisible();
  const authorSession = await page.request.post('/api/novel/session', { data:{ role:'author' }, headers:{ Origin: origin } });
  expect(authorSession.status()).toBe(200);
  await page.goto('/author');
  await expect(page.getByRole('heading',{name:'今天，写下新的章节。'})).toBeVisible();
  await page.getByLabel('作品名称').fill('浏览器创建的作品');
  await page.getByRole('button',{name:'保存草稿'}).click();
  await expect(page.getByRole('status')).toContainText('已保存为草稿');
  await page.getByLabel('章节标题').fill('浏览器章节');
  await page.getByLabel('章节正文').fill('这是经过自动筛查的章节正文。');
  await page.getByRole('button',{name:'提交并自动筛查'}).click();
  await expect(page.getByRole('status')).toContainText('章节已通过自动筛查并发布');
  const adminSession = await page.request.post('/api/novel/session', { data:{ role:'admin' }, headers:{ Origin: origin } });
  expect(adminSession.status()).toBe(200);
  await page.goto('/novel-admin');
  await expect(page.getByRole('heading',{name:'内容与运营，清晰可追溯。'})).toBeVisible();
  await expect(page.getByText('活跃读者')).toBeVisible();
  await page.getByLabel('敏感词').fill('测试词条');
  await page.getByRole('button',{name:'添加'}).click();
  await expect(page.getByRole('status')).toContainText('敏感词已加入审核规则');
  await expect(page.getByText('测试词条')).toBeVisible();
});
