export const RBAC_CONFIG = {
  CACHE: {
    PERMISSION_CACHE_DURATION: 5 * 60 * 1000,
  },
  ROUTING: {
    DEFAULT_UNAUTH_REDIRECT: '/login',
    DEFAULT_FORBIDDEN_REDIRECT: '/403',
  },
  PERMISSION: {
    DEFAULT_PAGE_SIZE: 100,
    MAX_PAGE_SIZE: 1000,
  },
};
