export const ROUTES = {
  BOOKSTORE: '/',
  AUTHOR: '/author',
  NOVEL_ADMIN: '/novel-admin',
  COMPASS: '/compass',
  DASHBOARD: '/dashboard',
  DATA_CENTER: '/data-center',
  METRIC_DETAIL: '/metric-detail',
  TASK_SCHEDULE: '/task-schedule',
  TASK_SCHEDULE_COLLECTION_JOBS: '/task-schedule/collection-jobs',
  AGENT_WORKBENCH: '/agent-workbench',
  DATA_SOURCE: '/data-source',
  SCRAPING_RULE: '/scraping-rule',
  USER_PERMISSION: '/user-permission',
  ADMIN_USERS: '/admin/users',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_PERMISSIONS: '/admin/permissions',
  ADMIN_LOGIN_AUDIT: '/admin/login-audit',
  PROFILE: '/profile',
  SYSTEM_SETTINGS: '/system-settings',
} as const;
