package cn.edu.training.novel.service;

import cn.edu.training.novel.domain.Book;
import cn.edu.training.novel.domain.BookStatus;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import org.springframework.web.multipart.MultipartFile;

/**
 * Coordinates database metadata with a non-transactional object store. New objects are removed on
 * a database rollback; an old object is removed only after a successful database commit.
 */
@Service
public class CoverUploadService {
    private static final Logger LOGGER = LoggerFactory.getLogger(CoverUploadService.class);
    private final CatalogRepository catalogRepository;
    private final AuditTrail auditTrail;
    private final CoverObjectStorage storage;
    private final CoverImageValidator imageValidator;

    public CoverUploadService(
            CatalogRepository catalogRepository,
            AuditTrail auditTrail,
            CoverObjectStorage storage,
            CoverImageValidator imageValidator) {
        this.catalogRepository = catalogRepository;
        this.auditTrail = auditTrail;
        this.storage = storage;
        this.imageValidator = imageValidator;
    }

    @Transactional
    public Book upload(long authorId, long bookId, MultipartFile file) {
        Book existing = catalogRepository.findByIdForUpdate(bookId)
                .orElseThrow(() -> new java.util.NoSuchElementException("book not found"));
        if (existing.authorId() != authorId) throw new SecurityException("resource does not belong to current author");
        if (!isEditable(existing.status())) {
            throw new IllegalStateException("book cover can only be edited while the book is a draft or rejected");
        }

        CoverImage image = imageValidator.validate(file);
        CoverObjectStorage.StoredCover uploaded = storage.store(image);
        try {
            Book updated = replaceCover(existing, uploaded.publicUrl());
            catalogRepository.updateBook(updated);
            auditTrail.record("upload cover book=" + updated.id()
                    + " author=" + authorId
                    + " width=" + image.width()
                    + " height=" + image.height()
                    + " type=" + image.contentType());
            scheduleReplacementCleanup(uploaded.publicUrl(), existing.cover());
            return updated;
        } catch (RuntimeException exception) {
            // The database transaction will roll back. Since this object was just generated by us,
            // it is safe to compensate immediately and it can never refer to an arbitrary cover URL.
            deleteNewObjectQuietly(uploaded.publicUrl(), "after database update failure");
            throw exception;
        }
    }

    private void scheduleReplacementCleanup(String newCoverUrl, String formerCoverUrl) {
        if (!TransactionSynchronizationManager.isSynchronizationActive()) {
            deleteFormerObjectQuietly(formerCoverUrl);
            return;
        }
        TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
            @Override
            public void afterCompletion(int status) {
                if (status == STATUS_COMMITTED) {
                    deleteFormerObjectQuietly(formerCoverUrl);
                } else {
                    deleteNewObjectQuietly(newCoverUrl, "after transaction rollback");
                }
            }
        });
    }

    private void deleteFormerObjectQuietly(String publicUrl) {
        if (!storage.isManaged(publicUrl)) return;
        try {
            storage.deleteManaged(publicUrl);
        } catch (RuntimeException exception) {
            // The committed row already references the new object. Retrying lifecycle cleanup must
            // never turn a successful author edit into a failed request or target a non-managed URL.
            LOGGER.warn("Could not delete former managed cover object after commit ({}).", exception.getClass().getSimpleName());
        }
    }

    private void deleteNewObjectQuietly(String publicUrl, String context) {
        if (!storage.isManaged(publicUrl)) return;
        try {
            storage.deleteManaged(publicUrl);
        } catch (RuntimeException exception) {
            LOGGER.warn("Could not compensate new managed cover {} ({}).", context, exception.getClass().getSimpleName());
        }
    }

    private static boolean isEditable(BookStatus status) {
        return status == BookStatus.DRAFT || status == BookStatus.REJECTED;
    }

    private static Book replaceCover(Book book, String cover) {
        return new Book(
                book.id(), book.title(), book.author(), book.category(), book.words(), book.serialStatus(),
                book.synopsis(), cover, book.status(), book.authorId(), book.heat(), book.purchasePrice());
    }
}
