package cn.edu.training.novel.service;

import cn.edu.training.novel.domain.Book;
import cn.edu.training.novel.domain.BookCoverCandidate;
import cn.edu.training.novel.domain.BookStatus;
import cn.edu.training.novel.domain.CoverUploadResult;
import java.util.Objects;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import org.springframework.web.multipart.MultipartFile;

/**
 * Coordinates a cover binding with a non-transactional object store. The media registry owns
 * previous assets and their deferred garbage collection; this service compensates only a newly
 * uploaded object when its surrounding database transaction cannot commit.
 */
@Service
public class CoverUploadService {
    private final CatalogRepository catalogRepository;
    private final AuditTrail auditTrail;
    private final CoverObjectStorage storage;
    private final CoverImageValidator imageValidator;
    private final MediaAssetService mediaAssets;

    public CoverUploadService(
            CatalogRepository catalogRepository,
            AuditTrail auditTrail,
            CoverObjectStorage storage,
            CoverImageValidator imageValidator,
            MediaAssetService mediaAssets) {
        this.catalogRepository = catalogRepository;
        this.auditTrail = auditTrail;
        this.storage = storage;
        this.imageValidator = imageValidator;
        this.mediaAssets = Objects.requireNonNull(mediaAssets, "mediaAssets");
    }

    @Transactional
    public CoverUploadResult upload(long authorId, long bookId, MultipartFile file) {
        Book existing = catalogRepository.findByIdForUpdate(bookId)
                .orElseThrow(() -> new java.util.NoSuchElementException("book not found"));
        if (existing.authorId() != authorId) throw new SecurityException("resource does not belong to current author");
        CoverImage image = imageValidator.validate(file);
        if (existing.status() == BookStatus.PUBLISHED) {
            BookCoverCandidate candidate = mediaAssets.stagePublishedBookCoverCandidate(authorId, existing, image);
            return new CoverUploadResult(existing, candidate);
        }
        if (!isEditable(existing.status())) {
            throw new IllegalStateException("book cover can only be edited while the book is a draft or rejected");
        }
        CoverObjectStorage.StoredCover uploaded = storage.store(image);
        try {
            mediaAssets.registerAuthorBookCover(authorId, existing.id(), uploaded, image);
            auditTrail.record("upload cover book=" + existing.id()
                    + " author=" + authorId
                    + " width=" + image.width()
                    + " height=" + image.height()
                    + " type=" + image.contentType());
            scheduleNewObjectRollbackCleanup(uploaded.publicUrl());
            return new CoverUploadResult(existing, null);
        } catch (RuntimeException exception) {
            // The database transaction will roll back. Since this object was just generated by us,
            // it is safe to compensate immediately and it can never refer to an arbitrary cover URL.
            deleteNewObjectQuietly(uploaded.publicUrl());
            throw exception;
        }
    }

    /** The registry owns the former asset's grace period; this only compensates a rolled-back upload. */
    private void scheduleNewObjectRollbackCleanup(String newCoverUrl) {
        if (!TransactionSynchronizationManager.isSynchronizationActive()) return;
        TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
            @Override
            public void afterCompletion(int status) {
                if (status != STATUS_COMMITTED) deleteNewObjectQuietly(newCoverUrl);
            }
        });
    }

    private void deleteNewObjectQuietly(String publicUrl) {
        if (!storage.isManaged(publicUrl)) return;
        try {
            storage.deleteManaged(publicUrl);
        } catch (RuntimeException ignored) {
            // Object-store inventory/GC is the final recovery path after a transient compensation failure.
        }
    }

    private static boolean isEditable(BookStatus status) {
        return status == BookStatus.DRAFT || status == BookStatus.REJECTED;
    }

}
